name: Lint Terraform

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**.tf'
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**.tf'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Terraform formatting
        run: terraform fmt -check -recursive
