name: Apply Account Requests
on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**.tf'
 
permissions:
  id-token: write
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform   # 👈 run Terraform from ./terraform folder
    permissions:
      id-token: write
      contents: read
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::314431539167:role/AFTGitHubRole
          aws-region: us-east-1
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
 
      - name: Terraform Init
        run: terraform init -upgrade
 
      - name: Terraform Plan
        run: terraform plan -out=tfplan
 
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
