name: Terraform Lint

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.tf'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6   # or 1.7.x if consistent
      - run: terraform fmt -check -recursive
