name: Validate Terraform (AFT Account Request)

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**.tf'
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**.tf'

permissions:
  contents: read

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # 🚨 Skip terraform init (since modules don't exist in repo)
      - name: Terraform Validate (syntax only)
        run: terraform validate
